"""
Tests for the PGN viewer HTML generated by build_pgn_viewer().

These tests guard the cross-browser fix: piece defs must live *inside*
#gv-board so that <use> references injected via innerHTML always resolve
within the same SVG tree (Firefox drops cross-SVG innerHTML references).
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from analyzer import GameAnalysis, MoveAnalysis
from outputs import build_pgn_viewer

START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
AFTER_E4  = "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1"

PIECE_IDS = ["gv-P", "gv-N", "gv-B", "gv-R", "gv-Q", "gv-K",
             "gv-p", "gv-n", "gv-b", "gv-r", "gv-q", "gv-k"]


def make_game() -> GameAnalysis:
    move = MoveAnalysis(
        ply=1, move_number=1, side="White",
        san="e4", uci="e2e4",
        fen_before=START_FEN, fen_after=AFTER_E4,
        eval_before_cp=20, mate_before=None,
        eval_after_cp=25, mate_after=None,
        best_move_san="e4", best_move_uci="e2e4",
        best_pv_san="1. e4", cp_loss=0,
    )
    return GameAnalysis(
        headers={"White": "Alice", "Black": "Bob", "Result": "*"},
        moves=[move],
        result="*",
        final_eval_cp=25,
        final_mate=None,
    )


def _board_svg_content(html: str) -> str:
    """Return the full text of the <svg id="gv-board"> element."""
    start = html.index('<svg id="gv-board"')
    depth = 0
    i = start
    while i < len(html):
        if html[i:i+4] == "<svg":
            depth += 1
            i += 4
        elif html[i:i+6] == "</svg>":
            depth -= 1
            if depth == 0:
                return html[start : i + 6]
            i += 6
        else:
            i += 1
    raise ValueError("No closing </svg> found for #gv-board")


# ---------------------------------------------------------------------------
# Cycle 1 — piece defs inside #gv-board (tracer bullet)
# ---------------------------------------------------------------------------

def test_piece_defs_are_inside_board_svg():
    """All 12 piece defs must be embedded inside <svg id="gv-board">.
    Cross-SVG <use> references via innerHTML don't resolve in Firefox."""
    html = build_pgn_viewer(make_game())
    board = _board_svg_content(html)
    assert 'id="gv-P"' in board, "White pawn def must be inside #gv-board"


# ---------------------------------------------------------------------------
# Cycle 2 — no standalone hidden piece-defs SVG
# ---------------------------------------------------------------------------

def test_no_standalone_piece_defs_svg():
    """The separate position:absolute hidden SVG (old _piece_defs_svg output)
    must not appear — all defs now live inside the board SVG."""
    html = build_pgn_viewer(make_game())
    assert "position:absolute;width:0;height:0" not in html, \
        "Standalone hidden piece-defs SVG must be removed"


# ---------------------------------------------------------------------------
# Cycle 3 — all 12 piece types present inside the board SVG
# ---------------------------------------------------------------------------

def test_all_twelve_piece_defs_inside_board_svg():
    """Every piece type (both colours) must have a def inside #gv-board."""
    html = build_pgn_viewer(make_game())
    board = _board_svg_content(html)
    missing = [pid for pid in PIECE_IDS if f'id="{pid}"' not in board]
    assert not missing, f"Missing piece defs inside #gv-board: {missing}"


# ---------------------------------------------------------------------------
# Cycle 4 — JS renderBoard preserves defs across re-renders
# ---------------------------------------------------------------------------

def test_renderboard_js_preserves_defs():
    """The embedded JS must save and restore the <defs> node before
    overwriting boardSvg.innerHTML, or pieces disappear after first click."""
    html = build_pgn_viewer(make_game())
    assert "querySelector('defs')" in html or 'querySelector("defs")' in html, \
        "JS renderBoard must use querySelector('defs') to preserve piece defs"
