"""
DEVELOPER / MAINTENANCE TOOL — not part of the shipped Greco product.

File already-reported PGNs into the 'Games with Reports' sub-folder.

Greco's GUI and CLI file a PGN into '<Chess Game Files>\\Games with Reports'
automatically the moment its report is written (outputs.archive_reported_pgn).
This script is the BACKUP PROTOCOL for everything that path misses: reports
generated by the web app, reports generated before the auto-filing existed, or
any run where the move failed. It is safe to run at any time, repeatedly.

For every *.pgn sitting DIRECTLY in the library root it parses the game's PGN
headers, derives the report name Greco would have used (outputs.report_basename),
and looks for a matching report folder in the reports library. Matches are moved
into 'Games with Reports'; everything else is left exactly where it is.

Deliberately conservative:
  * multi-game collection files are never moved (only single-game files);
  * a report folder counts only if it actually contains a .md or .html report;
  * matching is by exact report name, with one legacy fallback — old report
    folders named just '<White> vs <Black>' (no year) match on the player pair;
  * files are moved with outputs.archive_reported_pgn (same collision rules as
    the automatic path). Sub-folders are never scanned or touched.

Known limit (inherited from Greco's report naming): two different games between
the same players in the same year + time-control share one report name, so a
report for one counts as a report for both.

Usage:
    set PYTHONUTF8=1
    python tools\\file_reported_pgns.py --dry-run    # show what would move
    python tools\\file_reported_pgns.py              # actually move
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Dict, List, Optional, Tuple

GRECO_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(GRECO_DIR))

import chess.pgn  # noqa: E402

from outputs import (  # noqa: E402
    REPORTED_GAMES_DIRNAME,
    archive_reported_pgn,
    default_reports_dir,
    pgn_library_dir,
    report_basename,
)


def _resolve_reports_dir(override: Optional[str]) -> Path:
    """--reports flag → config.json 'reports_dir' → outputs.default_reports_dir()."""
    if override:
        return Path(override)
    cfg_path = GRECO_DIR / "config.json"
    if cfg_path.is_file():
        try:
            cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
            if cfg.get("reports_dir"):
                return Path(cfg["reports_dir"])
        except Exception:
            pass
    return default_reports_dir()


def _norm(name: str) -> str:
    """Normalize a report/folder name for comparison: case, '.', ',' and runs of
    whitespace are insignificant ('Andrei Volokitin vs Vassily Ivanchuk' ==
    'Andrei Volokitin vs. Vassily Ivanchuk')."""
    name = name.lower().replace(".", "").replace(",", "")
    return re.sub(r"\s+", " ", name).strip()


def _read_single_game_headers(pgn_path: Path) -> Tuple[Optional[dict], int]:
    """Return (headers of the first game, number of games in the file).
    headers is None if the file has no parseable game."""
    with pgn_path.open(encoding="utf-8", errors="replace") as fh:
        first = chess.pgn.read_headers(fh)
        if first is None:
            return None, 0
        count = 1
        while chess.pgn.read_headers(fh) is not None:
            count += 1
            if count > 1:
                break  # all we need to know is "more than one"
    return dict(first), count


def _report_folders(reports_dir: Path) -> Dict[str, str]:
    """Map normalized folder name → real folder name, for folders that actually
    contain a report (.md or .html). Essay folders are not game reports."""
    found: Dict[str, str] = {}
    if not reports_dir.is_dir():
        return found
    for entry in reports_dir.iterdir():
        if not entry.is_dir() or entry.name.startswith("essay_"):
            continue
        has_report = any(p.suffix.lower() in (".md", ".html") for p in entry.iterdir())
        if has_report:
            found[_norm(entry.name)] = entry.name
    return found


def _match(headers: dict, folders: Dict[str, str]) -> Optional[str]:
    """Return the matching report folder's real name, or None."""
    basename = report_basename(SimpleNamespace(headers=headers))
    exact = folders.get(_norm(basename))
    if exact:
        return exact
    # Legacy fallback: old folders were named '<White> vs <Black>' with no
    # year/category suffix — match those on the bare player pair only.
    white = (headers.get("White") or "White").strip() or "White"
    black = (headers.get("Black") or "Black").strip() or "Black"
    return folders.get(_norm(f"{white} vs {black}"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[3])
    ap.add_argument("--library", default=None,
                    help="PGN library root (default: Documents\\Chess Game Files)")
    ap.add_argument("--reports", default=None,
                    help="Reports folder (default: config.json reports_dir, else Documents\\Greco Reports)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Report what would move without moving anything")
    args = ap.parse_args()

    library = Path(args.library) if args.library else pgn_library_dir()
    reports_dir = _resolve_reports_dir(args.reports)
    if not library.is_dir():
        print(f"ERROR: PGN library not found: {library}", file=sys.stderr)
        return 2

    folders = _report_folders(reports_dir)
    print(f"Library: {library}")
    print(f"Reports: {reports_dir}  ({len(folders)} report folders)")
    print(f"Mode:    {'DRY RUN — nothing will move' if args.dry_run else 'apply'}\n")

    filed: List[str] = []
    kept: List[str] = []
    skipped: List[str] = []

    for pgn in sorted(p for p in library.iterdir()
                      if p.is_file() and p.suffix.lower() == ".pgn"):
        try:
            headers, count = _read_single_game_headers(pgn)
        except OSError as exc:
            skipped.append(f"{pgn.name}  (unreadable: {exc})")
            continue
        if headers is None:
            skipped.append(f"{pgn.name}  (no parseable game)")
            continue
        if count > 1:
            skipped.append(f"{pgn.name}  (multi-game collection — left in place)")
            continue
        folder = _match(headers, folders)
        if not folder:
            kept.append(pgn.name)
            continue
        if args.dry_run:
            filed.append(f"{pgn.name}  →  report: '{folder}'")
        else:
            moved = archive_reported_pgn(pgn, library_dir=library)
            if moved:
                filed.append(f"{pgn.name}  →  report: '{folder}'")
            else:
                skipped.append(f"{pgn.name}  (matched '{folder}' but move failed)")

    verb = "WOULD FILE" if args.dry_run else "FILED"
    print(f"{verb} into '{REPORTED_GAMES_DIRNAME}' ({len(filed)}):")
    for line in filed:
        print(f"  {line}")
    print(f"\nKEPT in root — no report yet ({len(kept)}):")
    for name in kept:
        print(f"  {name}")
    if skipped:
        print(f"\nSKIPPED ({len(skipped)}):")
        for line in skipped:
            print(f"  {line}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
